# coding=utf-8
"""HTML report generation and email notification.

Imports tier display constants from ``news.constants`` (single source
of truth shared with the web frontend).
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, formatdate
from typing import Dict, List, Optional

from news.constants import TIER_LABELS, TIER_COLORS, TIER_BG


def build_html_report(
    grouped_items: Dict[str, List[Dict]],
    date: str,
    time_str: str,
    total_count: int,
) -> str:
    """Generate a simple, clean HTML report.

    Args:
        grouped_items: {group_name: [item_dict, ...]} from match_and_group()
        date: YYYY-MM-DD
        time_str: HH:MM
        total_count: Total items in report

    Returns:
        HTML string
    """
    rows_html = ""
    tier_labels = {1: "T1", 2: "T2", 3: "T3", 4: "T4"}
    tier_colors = {1: "#22c55e", 2: "#3b82f6", 3: "#f59e0b", 4: "#94a3b8"}

    for group_name, items in grouped_items.items():
        if not items:
            continue
        label = group_name if group_name != "__unmatched__" else "其他新闻"
        rows_html += (
            f'<h3 style="color:#3b82f6;margin-top:24px;border-bottom:1px solid #1e293b;padding-bottom:8px;">'
            f'{label} <span style="font-size:14px;color:#64748b;">({len(items)})</span></h3>\n'
        )
        rows_html += (
            '<table style="width:100%;border-collapse:collapse;font-size:14px;">\n'
        )

        for item in items:
            title = item.get("title", "")
            source = item.get("source_name", "")
            source_type = item.get("source_type", "hotlist")
            url = item.get("url", "")
            rank = item.get("rank", "")
            summary = item.get("summary", "")
            tier = item.get("tier", 4)
            tier_color = tier_colors.get(tier, "#94a3b8")
            tier_label = tier_labels.get(tier, "T4")

            if source_type == "rss":
                type_label = "[RSS]"
            elif rank:
                type_label = f"[#{rank}]"
            else:
                type_label = ""

            title_html = (
                f'<a href="{url}" style="color:#e2e8f0;text-decoration:none;">{title}</a>'
                if url
                else title
            )

            rows_html += (
                f'<tr style="border-bottom:1px solid #1e293b;">'
                f'<td style="padding:8px;color:#64748b;white-space:nowrap;width:60px;">{type_label}</td>'
                f'<td style="padding:8px;">'
                f'<span style="color:{tier_color};font-size:11px;margin-right:6px;">[{tier_label}]</span>'
                f'{title_html}</td>'
                f'<td style="padding:8px;color:#64748b;white-space:nowrap;width:100px;">{source}</td>'
                f'</tr>\n'
            )
            if summary:
                rows_html += (
                    f'<tr style="border-bottom:1px solid #1e293b;">'
                    f'<td></td>'
                    f'<td colspan="2" style="padding:4px 8px 8px;color:#94a3b8;font-size:13px;">'
                    f'{summary[:200]}</td>'
                    f'</tr>\n'
                )

        rows_html += "</table>\n"

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>News Report — {date} {time_str}</title>
<style>
  body {{ background:#0f172a; color:#e2e8f0; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
         max-width:800px; margin:0 auto; padding:20px; }}
  h1 {{ font-size:22px; }}
  h2 {{ font-size:16px; color:#94a3b8; font-weight:400; }}
  h3 {{ font-size:15px; }}
  a:hover {{ text-decoration:underline; }}
</style>
</head>
<body>
<h1>\U0001f4f0 新闻速报</h1>
<h2>{date} {time_str} · {total_count} 条新闻 · {len(grouped_items)} 个分组</h2>
{rows_html}
<p style="margin-top:32px;color:#475569;font-size:12px;">Generated by NewsNow Crawler</p>
</body>
</html>"""
    return html


def send_email(
    html_content: str,
    smtp_server: str,
    smtp_port: int,
    from_addr: str,
    to_addr: str,
    password: str,
    subject: Optional[str] = None,
) -> bool:
    """Send HTML email via SMTP.

    Returns:
        True on success, False on failure.
    """
    if not subject:
        subject = "\U0001f4f0 新闻速报"

    try:
        msg = MIMEMultipart("alternative")
        msg["From"] = formataddr(("NewsNow Crawler", from_addr))
        msg["To"] = to_addr
        msg["Subject"] = subject
        msg["Date"] = formatdate(localtime=True)

        # Plain text fallback
        text_part = MIMEText(
            "请使用支持 HTML 的邮件客户端查看。",
            "plain",
            "utf-8",
        )
        msg.attach(text_part)

        # HTML part
        html_part = MIMEText(html_content, "html", "utf-8")
        msg.attach(html_part)

        # Connect and send
        if smtp_port == 465:
            server = smtplib.SMTP_SSL(smtp_server, smtp_port, timeout=30)
        else:
            server = smtplib.SMTP(smtp_server, smtp_port, timeout=30)
            server.starttls()

        server.login(from_addr, password)
        recipients = [addr.strip() for addr in to_addr.split(",") if addr.strip()]
        server.sendmail(from_addr, recipients, msg.as_string())
        server.quit()

        print(f"[Email] Sent to {len(recipients)} recipient(s)")
        return True

    except Exception as e:
        print(f"[Email] Failed: {e}")
        return False


def run_notifier(config: dict) -> None:
    """Run the full notification pipeline.

    1. Download daily SQLite DB from S3
    2. Query unnotified items
    3. Match keywords and group
    4. Build HTML report
    5. Send email
    6. Mark items as notified and upload back

    This is the entry point used by both ``cli.py notify`` (GitHub
    Actions) and any future daemon-triggered notification.
    """
    import os

    from news.keywords import load_frequency_words, match_and_group
    from storage.sqlite import Storage
    from utils import format_date_folder, format_time_display, DEFAULT_TIMEZONE

    timezone = config.get("app", {}).get("timezone", DEFAULT_TIMEZONE)
    date = format_date_folder(timezone)
    time_str = format_time_display(timezone)

    print(f"=== Notifier === {date} {time_str}")

    # Init storage
    storage_config = config.get("storage", {})
    storage = Storage(
        data_dir=storage_config.get("local", {}).get("data_dir", "output"),
        timezone=timezone,
        s3_config=storage_config.get("remote") or None,
    )

    # Get unnotified items
    rows = storage.get_unnotified(date)
    if not rows:
        print("No new items to notify")
        storage.cleanup()
        return

    # Convert rows to dicts
    items = [dict(row) for row in rows]
    print(f"Unnotified items: {len(items)}")

    # Load keywords and match
    freq_path = config.get("notification", {}).get(
        "frequency_words", "news/frequency_words.txt"
    )
    if not os.path.exists(freq_path):
        # Fall back to root-level file for backward compatibility
        freq_path = "frequency_words.txt"
    if os.path.exists(freq_path):
        word_groups, filter_words, global_filters = load_frequency_words(freq_path)
        max_per = config.get("notification", {}).get("max_news_per_keyword", 0)
        grouped = match_and_group(items, word_groups, global_filters, max_per)
        print(f"Matched groups: {list(grouped.keys())}")
    else:
        grouped = {"全部新闻": items}

    # Build HTML report
    html = build_html_report(grouped, date, time_str, len(items))

    # Send email
    email_config = config.get("notification", {}).get("email", {})
    smtp_server = email_config.get("smtp_server", "smtp.qq.com")
    smtp_port = email_config.get("smtp_port", 587)
    from_addr = email_config.get("from_addr", "")
    to_addr = email_config.get("to_addr", "")
    password = email_config.get("password") or os.environ.get("EMAIL_PASSWORD", "")

    if not all([from_addr, to_addr, password]):
        print("[Email] Missing config — skipping send")
    else:
        send_email(html, smtp_server, smtp_port, from_addr, to_addr, password)

    # Mark as notified
    storage.mark_notified(date)

    storage.cleanup()
    print("=== Done ===")
